// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: sls.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     *uint32        `protobuf:"varint,1,req,name=Time" json:"Time,omitempty"` // UNIX Time Format
	Contents []*Log_Content `protobuf:"bytes,2,rep,name=Contents" json:"Contents,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_sls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_sls_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *Log) GetContents() []*Log_Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

type LogTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value *string `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
}

func (x *LogTag) Reset() {
	*x = LogTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTag) ProtoMessage() {}

func (x *LogTag) ProtoReflect() protoreflect.Message {
	mi := &file_sls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTag.ProtoReflect.Descriptor instead.
func (*LogTag) Descriptor() ([]byte, []int) {
	return file_sls_proto_rawDescGZIP(), []int{1}
}

func (x *LogTag) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *LogTag) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type LogGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs     []*Log    `protobuf:"bytes,1,rep,name=Logs" json:"Logs,omitempty"`
	Reserved *string   `protobuf:"bytes,2,opt,name=Reserved" json:"Reserved,omitempty"` // reserved fields
	Topic    *string   `protobuf:"bytes,3,opt,name=Topic" json:"Topic,omitempty"`
	Source   *string   `protobuf:"bytes,4,opt,name=Source" json:"Source,omitempty"`
	LogTags  []*LogTag `protobuf:"bytes,6,rep,name=LogTags" json:"LogTags,omitempty"`
}

func (x *LogGroup) Reset() {
	*x = LogGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sls_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogGroup) ProtoMessage() {}

func (x *LogGroup) ProtoReflect() protoreflect.Message {
	mi := &file_sls_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogGroup.ProtoReflect.Descriptor instead.
func (*LogGroup) Descriptor() ([]byte, []int) {
	return file_sls_proto_rawDescGZIP(), []int{2}
}

func (x *LogGroup) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LogGroup) GetReserved() string {
	if x != nil && x.Reserved != nil {
		return *x.Reserved
	}
	return ""
}

func (x *LogGroup) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *LogGroup) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *LogGroup) GetLogTags() []*LogTag {
	if x != nil {
		return x.LogTags
	}
	return nil
}

type Log_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value *string `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
}

func (x *Log_Content) Reset() {
	*x = Log_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sls_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Content) ProtoMessage() {}

func (x *Log_Content) ProtoReflect() protoreflect.Message {
	mi := &file_sls_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Content.ProtoReflect.Descriptor instead.
func (*Log_Content) Descriptor() ([]byte, []int) {
	return file_sls_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Log_Content) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *Log_Content) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

var File_sls_proto protoreflect.FileDescriptor

var file_sls_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x03, 0x4c,
	0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x1a, 0x31, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x30, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x54, 0x61, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x18, 0x0a, 0x04, 0x4c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x04, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4c, 0x6f, 0x67, 0x54, 0x61, 0x67,
	0x52, 0x07, 0x4c, 0x6f, 0x67, 0x54, 0x61, 0x67, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61,
	0x70, 0x69,
}

var (
	file_sls_proto_rawDescOnce sync.Once
	file_sls_proto_rawDescData = file_sls_proto_rawDesc
)

func file_sls_proto_rawDescGZIP() []byte {
	file_sls_proto_rawDescOnce.Do(func() {
		file_sls_proto_rawDescData = protoimpl.X.CompressGZIP(file_sls_proto_rawDescData)
	})
	return file_sls_proto_rawDescData
}

var file_sls_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sls_proto_goTypes = []interface{}{
	(*Log)(nil),         // 0: Log
	(*LogTag)(nil),      // 1: LogTag
	(*LogGroup)(nil),    // 2: LogGroup
	(*Log_Content)(nil), // 3: Log.Content
}
var file_sls_proto_depIdxs = []int32{
	3, // 0: Log.Contents:type_name -> Log.Content
	0, // 1: LogGroup.Logs:type_name -> Log
	1, // 2: LogGroup.LogTags:type_name -> LogTag
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sls_proto_init() }
func file_sls_proto_init() {
	if File_sls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sls_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sls_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sls_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sls_proto_goTypes,
		DependencyIndexes: file_sls_proto_depIdxs,
		MessageInfos:      file_sls_proto_msgTypes,
	}.Build()
	File_sls_proto = out.File
	file_sls_proto_rawDesc = nil
	file_sls_proto_goTypes = nil
	file_sls_proto_depIdxs = nil
}
